

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.27.243.243:3366/dwz?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: =987599519@

  redis:
    host: 175.27.243.243
    password: 213879
    port: 6379
    database: 1
    timeout: 10000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    name: ./log/ShortUrl
  level:
    root: info